project:
  type: book
  output-dir: docs
  
book:
  title: "Gift Study-Supplement"
  author:
    - name: Timothy P Hofer
      affiliations: University of Michigan
      orcid: 'https://orcid.org/0000-0003-0434-8787'
    - name: Steven J Katz
      affiliations: University of Michigan
      orcid: 'https://orcid.org/0000-0002-1151-861X'
    - name: Paul Abrahamse
      affiliations: University of Michigan
      orcid: 'https://orcid.org/0000-0001-7433-153X' 
  date: "10/1/2025"
  date-format: long
  search: true
  cover-image: img/gift_logo.png
  repo-url: https://github.com/intmed-cansort/gift-main
  site-url: https://intmed-cansort.github.io/gift-main/
  repo-actions: [source]
  sidebar:
    collapse-level: 2
    pinnned: true
  chapters:
    - index.qmd
    - study_pop.qmd
    - protocol_flow.qmd
    - flow_chart.qmd
    - interventions.qmd
    - part: "Data & Descriptives"
      chapters:
      - data.qmd
      - descriptives.qmd
    - part: "Protocol Results"
      chapters: 
      - main.qmd
      - invitation.qmd
      - communication.qmd
      - main_results_table.qmd
    - part: "Additional analyses"
      chapters:
      - model_checks.qmd
      - exploratory.qmd
    - part: "Reviewer requested"
      chapters:
      - num_denom.qmd
      - interactions.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Timothy Hofer (for the CANSORT team)"
code-fold: true
number-depth: 3
toc-depth: 5
reference-location: margin
execute:
  freeze: auto
format:
  html:
    date-modified: last-modified
    theme: 
      - cosmo
      - custom_doc.scss
    grid:
      sidebar-width: 210px
      body-width: 900px
    code-fold: true
    code-summary: "code"
    sidebar:
      collapse-level: 3
      pinned: true
bibliography: references.bib
crossref:
  custom:
    - kind: float
      key: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
    - kind: float
      key: supptbl
      reference-prefix: Table S
      space-before-numbering: false
      latex-list-of-description: Supplementary Table
editor: source
